[package]
name = "advent_of_code_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
shared_types = {path="./shared_types"}
day1 = {path="./day1"}
day2 = {path="./day2"}
day3 = {path="./day3"}
day4 = {path="./day4"}